<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Cheeseburger Combo',
                'description' => 'Juicy cheeseburger served with fries and a soda.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Margherita Pizza',
                'description' => 'Classic Italian pizza with tomato sauce, mozzarella, and basil.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Chicken Alfredo Pasta',
                'description' => 'Creamy fettuccine pasta with grilled chicken and parmesan.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Caesar Salad',
                'description' => 'Fresh romaine lettuce with Caesar dressing, croutons, and parmesan.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Grilled Steak',
                'description' => 'Tender grilled steak served with mashed potatoes and steamed vegetables.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Chicken Shawarma Wrap',
                'description' => 'Grilled chicken, garlic sauce, and pickles wrapped in pita bread.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Beef Kebab Plate',
                'description' => 'Grilled beef kebabs served with rice and a side of salad.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Fish and Chips',
                'description' => 'Golden-fried fish fillets served with crispy fries and tartar sauce.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Buffalo Wings',
                'description' => 'Spicy buffalo wings served with blue cheese dressing.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Veggie Burger',
                'description' => 'Plant-based burger patty with lettuce, tomato, and vegan mayo.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Seafood Paella',
                'description' => 'Spanish rice dish with shrimp, mussels, and calamari.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Grilled Chicken Sandwich',
                'description' => 'Marinated grilled chicken with lettuce, tomato, and mayo.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Spaghetti Bolognese',
                'description' => 'Classic spaghetti with hearty meat sauce.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Lamb Chops',
                'description' => 'Succulent lamb chops served with roasted vegetables.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Sushi Platter',
                'description' => 'Assorted sushi rolls with soy sauce and pickled ginger.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Vegetable Stir Fry',
                'description' => 'Stir-fried vegetables with soy sauce and noodles.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'BBQ Ribs',
                'description' => 'Tender BBQ ribs served with coleslaw and cornbread.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Margarita Cocktail',
                'description' => 'Refreshing lime and tequila cocktail.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Tacos Al Pastor',
                'description' => 'Mexican-style tacos with marinated pork and pineapple.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Pancake Stack',
                'description' => 'Fluffy pancakes with maple syrup and butter.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 1,
            ],
            [
                'name' => 'Smartphone',
                'description' => 'Latest model with advanced features and 128GB storage.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Laptop',
                'description' => 'High-performance laptop with 16GB RAM and 512GB SSD.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Bluetooth Headphones',
                'description' => 'Noise-cancelling wireless headphones with 20 hours of battery life.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Smart TV',
                'description' => '4K Ultra HD Smart TV with built-in streaming apps.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Gaming Console',
                'description' => 'Next-generation gaming console with 4K gaming support.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Tablet',
                'description' => 'Lightweight tablet with 10-inch screen and 64GB storage.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Smartwatch',
                'description' => 'Stylish smartwatch with health tracking and notifications.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Wireless Earbuds',
                'description' => 'Compact wireless earbuds with touch controls and charging case.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'External Hard Drive',
                'description' => '1TB external hard drive for secure data storage.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Mechanical Keyboard',
                'description' => 'RGB backlit mechanical keyboard for gaming and productivity.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Gaming Mouse',
                'description' => 'High-precision gaming mouse with customizable buttons.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Digital Camera',
                'description' => 'Compact digital camera with 20MP sensor and 4K video recording.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Printer',
                'description' => 'Wireless printer with scanning and copying functions.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Drone',
                'description' => 'Compact drone with HD camera and 30-minute flight time.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Power Bank',
                'description' => 'Portable power bank with 10,000mAh capacity.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Router',
                'description' => 'High-speed Wi-Fi router with dual-band support.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Speaker',
                'description' => 'Bluetooth speaker with powerful bass and 10-hour battery.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'VR Headset',
                'description' => 'Immersive virtual reality headset with motion tracking.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Portable Projector',
                'description' => 'Compact projector for home cinema and presentations.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Digital Watch',
                'description' => 'Classic digital watch with stopwatch and alarm functions.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Pain Relief Tablets',
                'description' => 'Effective tablets for headache and minor aches.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Cough Syrup',
                'description' => 'Soothing syrup for dry and wet cough.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Vitamin C Tablets',
                'description' => 'Boosts immunity and reduces fatigue.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Hand Sanitizer',
                'description' => 'Kills 99.9% of germs. Alcohol-based formula.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Face Masks',
                'description' => 'Pack of 50 disposable 3-ply face masks.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Antiseptic Cream',
                'description' => 'For minor cuts, burns, and skin irritations.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Digital Thermometer',
                'description' => 'Accurate temperature readings in seconds.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'First Aid Kit',
                'description' => 'Complete kit with bandages, antiseptics, and tools.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Blood Pressure Monitor',
                'description' => 'Easy-to-use device for monitoring blood pressure.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Antihistamine Tablets',
                'description' => 'Relieves symptoms of allergies and hay fever.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Muscle Pain Gel',
                'description' => 'Fast relief for muscle and joint pain.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Multivitamins',
                'description' => 'Daily multivitamin tablets for overall health.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Baby Diapers',
                'description' => 'Pack of 30 ultra-absorbent baby diapers.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Calcium Supplements',
                'description' => 'Promotes strong bones and teeth.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Hair Growth Serum',
                'description' => 'Improves hair growth and reduces hair loss.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Nasal Spray',
                'description' => 'Relieves nasal congestion and sinus discomfort.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Energy Drinks',
                'description' => 'Pack of 4 energy drinks for a quick energy boost.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Antacid Tablets',
                'description' => 'Provides fast relief from heartburn and indigestion.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Sunscreen Lotion',
                'description' => 'SPF 50 sunscreen for effective sun protection.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Sleep Aid Tablets',
                'description' => 'Helps improve sleep quality naturally.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 3,
            ],
            [
                'name' => 'Fresh Milk',
                'description' => '1-liter pack of fresh and pure cow milk.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'White Bread',
                'description' => 'Freshly baked sliced bread, perfect for sandwiches.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Eggs Pack',
                'description' => '12-pack of farm-fresh eggs.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Butter',
                'description' => '200g of creamy and unsalted butter.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Cheddar Cheese',
                'description' => '500g block of sharp cheddar cheese.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Chicken Breast',
                'description' => '1kg of fresh boneless chicken breast.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Rice (5kg)',
                'description' => 'Long-grain basmati rice, perfect for cooking.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Cooking Oil',
                'description' => '2-liter bottle of sunflower cooking oil.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Pasta',
                'description' => '500g pack of premium Italian spaghetti.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Tomato Ketchup',
                'description' => '1-liter bottle of rich and tangy tomato ketchup.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Instant Coffee',
                'description' => '200g jar of premium freeze-dried coffee.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Sugar (2kg)',
                'description' => 'Pure refined white sugar, ideal for sweetening.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Salt',
                'description' => '1kg pack of iodized table salt.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Potato Chips',
                'description' => 'Large pack of crispy salted potato chips.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Cereal',
                'description' => '500g box of whole grain breakfast cereal.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Fresh Apples',
                'description' => '1kg of fresh and juicy red apples.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Orange Juice',
                'description' => '1-liter carton of 100% pure orange juice.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Dishwashing Liquid',
                'description' => '1-liter bottle of powerful grease-fighting liquid.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Laundry Detergent',
                'description' => '5kg bag of effective and fragrant detergent powder.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Toilet Paper',
                'description' => 'Pack of 10 soft and absorbent toilet paper rolls.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 4,
            ],
            [
                'name' => 'Rose Essence Perfume',
                'description' => 'A luxurious perfume with a fresh rose fragrance.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Oud Al Arab',
                'description' => 'An exotic oud-based perfume with long-lasting aroma.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Vanilla Bliss',
                'description' => 'A sweet and comforting vanilla-scented perfume.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Citrus Splash',
                'description' => 'A refreshing perfume with notes of citrus and bergamot.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Lavender Mist',
                'description' => 'A calming lavender fragrance, perfect for everyday use.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Jasmine Bloom',
                'description' => 'A rich and enchanting jasmine-scented perfume.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Woody Musk',
                'description' => 'A masculine perfume with woody and musky notes.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Amber Glow',
                'description' => 'A warm and captivating amber-based fragrance.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Patchouli Dream',
                'description' => 'A bold and earthy patchouli perfume for unique individuals.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Mint Breeze',
                'description' => 'A cooling and invigorating mint-scented fragrance.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Ocean Wave',
                'description' => 'A marine-inspired perfume with hints of sea breeze.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Golden Sandalwood',
                'description' => 'A luxurious sandalwood perfume with a golden touch.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Floral Fantasy',
                'description' => 'A bouquet of floral scents blended in one bottle.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Spicy Oud',
                'description' => 'A unique oud fragrance with spicy undertones.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Euphoria',
                'description' => 'A vibrant and uplifting fruity-floral perfume.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Classic Musk',
                'description' => 'An all-time favorite musky perfume for elegance.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Oriental Spice',
                'description' => 'An oriental perfume with rich spicy aromas.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Green Tea Bliss',
                'description' => 'A refreshing perfume with green tea and citrus notes.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Luxury Rose Oud',
                'description' => 'A luxurious blend of rose and oud fragrances.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Coconut Paradise',
                'description' => 'A tropical coconut fragrance with sweet vanilla hints.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 5,
            ],
            [
                'name' => 'Cheeseburger Combo',
                'description' => 'Juicy cheeseburger served with fries and a soda.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Margherita Pizza',
                'description' => 'Classic Italian pizza with tomato sauce, mozzarella, and basil.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Chicken Alfredo Pasta',
                'description' => 'Creamy fettuccine pasta with grilled chicken and parmesan.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Caesar Salad',
                'description' => 'Fresh romaine lettuce with Caesar dressing, croutons, and parmesan.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Grilled Steak',
                'description' => 'Tender grilled steak served with mashed potatoes and steamed vegetables.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Chicken Shawarma Wrap',
                'description' => 'Grilled chicken, garlic sauce, and pickles wrapped in pita bread.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Beef Kebab Plate',
                'description' => 'Grilled beef kebabs served with rice and a side of salad.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Fish and Chips',
                'description' => 'Golden-fried fish fillets served with crispy fries and tartar sauce.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Buffalo Wings',
                'description' => 'Spicy buffalo wings served with blue cheese dressing.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Veggie Burger',
                'description' => 'Plant-based burger patty with lettuce, tomato, and vegan mayo.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Seafood Paella',
                'description' => 'Spanish rice dish with shrimp, mussels, and calamari.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Grilled Chicken Sandwich',
                'description' => 'Marinated grilled chicken with lettuce, tomato, and mayo.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Spaghetti Bolognese',
                'description' => 'Classic spaghetti with hearty meat sauce.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Lamb Chops',
                'description' => 'Succulent lamb chops served with roasted vegetables.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Sushi Platter',
                'description' => 'Assorted sushi rolls with soy sauce and pickled ginger.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Vegetable Stir Fry',
                'description' => 'Stir-fried vegetables with soy sauce and noodles.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'BBQ Ribs',
                'description' => 'Tender BBQ ribs served with coleslaw and cornbread.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Margarita Cocktail',
                'description' => 'Refreshing lime and tequila cocktail.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Tacos Al Pastor',
                'description' => 'Mexican-style tacos with marinated pork and pineapple.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Pancake Stack',
                'description' => 'Fluffy pancakes with maple syrup and butter.',
                'price' => rand(50, 6000),
                'quantity' => rand(6, 50),
                'store_id' => 6,
            ],
            [
                'name' => 'Smartphone',
                'description' => 'Latest model with advanced features and 178GB storage.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Laptop',
                'description' => 'High-performance laptop with 16GB RAM and 517GB SSD.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Bluetooth Headphones',
                'description' => 'Noise-cancelling wireless headphones with 70 hours of battery life.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Smart TV',
                'description' => '4K Ultra HD Smart TV with built-in streaming apps.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Gaming Console',
                'description' => 'Next-generation gaming console with 4K gaming support.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Tablet',
                'description' => 'Lightweight tablet with 10-inch screen and 64GB storage.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Smartwatch',
                'description' => 'Stylish smartwatch with health tracking and notifications.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Wireless Earbuds',
                'description' => 'Compact wireless earbuds with touch controls and charging case.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'External Hard Drive',
                'description' => '1TB external hard drive for secure data storage.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Mechanical Keyboard',
                'description' => 'RGB backlit mechanical keyboard for gaming and productivity.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Gaming Mouse',
                'description' => 'High-precision gaming mouse with customizable buttons.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Digital Camera',
                'description' => 'Compact digital camera with 70MP sensor and 4K video recording.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Printer',
                'description' => 'Wireless printer with scanning and copying functions.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Drone',
                'description' => 'Compact drone with HD camera and 30-minute flight time.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Power Bank',
                'description' => 'Portable power bank with 10,000mAh capacity.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Router',
                'description' => 'High-speed Wi-Fi router with dual-band support.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Speaker',
                'description' => 'Bluetooth speaker with powerful bass and 10-hour battery.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'VR Headset',
                'description' => 'Immersive virtual reality headset with motion tracking.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Portable Projector',
                'description' => 'Compact projector for home cinema and presentations.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 7,
            ],
            [
                'name' => 'Digital Watch',
                'description' => 'Classic digital watch with stopwatch and alarm functions.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 2,
            ],
            [
                'name' => 'Pain Relief Tablets',
                'description' => 'Effective tablets for headache and minor aches.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Cough Syrup',
                'description' => 'Soothing syrup for dry and wet cough.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Vitamin C Tablets',
                'description' => 'Boosts immunity and reduces fatigue.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Hand Sanitizer',
                'description' => 'Kills 99.9% of germs. Alcohol-based formula.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Face Masks',
                'description' => 'Pack of 50 disposable 8-ply face masks.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Antiseptic Cream',
                'description' => 'For minor cuts, burns, and skin irritations.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Digital Thermometer',
                'description' => 'Accurate temperature readings in seconds.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'First Aid Kit',
                'description' => 'Complete kit with bandages, antiseptics, and tools.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Blood Pressure Monitor',
                'description' => 'Easy-to-use device for monitoring blood pressure.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Antihistamine Tablets',
                'description' => 'Relieves symptoms of allergies and hay fever.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Muscle Pain Gel',
                'description' => 'Fast relief for muscle and joint pain.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Multivitamins',
                'description' => 'Daily multivitamin tablets for overall health.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Baby Diapers',
                'description' => 'Pack of 80 ultra-absorbent baby diapers.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Calcium Supplements',
                'description' => 'Promotes strong bones and teeth.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Hair Growth Serum',
                'description' => 'Improves hair growth and reduces hair loss.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Nasal Spray',
                'description' => 'Relieves nasal congestion and sinus discomfort.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Energy Drinks',
                'description' => 'Pack of 4 energy drinks for a quick energy boost.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Antacid Tablets',
                'description' => 'Provides fast relief from heartburn and indigestion.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Sunscreen Lotion',
                'description' => 'SPF 50 sunscreen for effective sun protection.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Sleep Aid Tablets',
                'description' => 'Helps improve sleep quality naturally.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 8,
            ],
            [
                'name' => 'Fresh Milk',
                'description' => '1-liter pack of fresh and pure cow milk.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'White Bread',
                'description' => 'Freshly baked sliced bread, perfect for sandwiches.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Eggs Pack',
                'description' => '12-pack of farm-fresh eggs.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Butter',
                'description' => '200g of creamy and unsalted butter.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Cheddar Cheese',
                'description' => '500g block of sharp cheddar cheese.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Chicken Breast',
                'description' => '1kg of fresh boneless chicken breast.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Rice (5kg)',
                'description' => 'Long-grain basmati rice, perfect for cooking.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Cooking Oil',
                'description' => '2-liter bottle of sunflower cooking oil.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Pasta',
                'description' => '500g pack of premium Italian spaghetti.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Tomato Ketchup',
                'description' => '1-liter bottle of rich and tangy tomato ketchup.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Instant Coffee',
                'description' => '200g jar of premium freeze-dried coffee.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Sugar (2kg)',
                'description' => 'Pure refined white sugar, ideal for sweetening.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Salt',
                'description' => '1kg pack of iodized table salt.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Potato Chips',
                'description' => 'Large pack of crispy salted potato chips.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Cereal',
                'description' => '500g box of whole grain breakfast cereal.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Fresh Apples',
                'description' => '1kg of fresh and juicy red apples.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Orange Juice',
                'description' => '1-liter carton of 100% pure orange juice.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Dishwashing Liquid',
                'description' => '1-liter bottle of powerful grease-fighting liquid.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Laundry Detergent',
                'description' => '5kg bag of effective and fragrant detergent powder.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Toilet Paper',
                'description' => 'Pack of 10 soft and absorbent toilet paper rolls.',
                'price' => rand(50, 1000),
                'quantity' => rand(1, 50),
                'store_id' => 9,
            ],
            [
                'name' => 'Rose Essence Perfume',
                'description' => 'A luxurious perfume with a fresh rose fragrance.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Oud Al Arab',
                'description' => 'An exotic oud-based perfume with long-lasting aroma.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Vanilla Bliss',
                'description' => 'A sweet and comforting vanilla-scented perfume.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Citrus Splash',
                'description' => 'A refreshing perfume with notes of citrus and bergamot.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Lavender Mist',
                'description' => 'A calming lavender fragrance, perfect for everyday use.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Jasmine Bloom',
                'description' => 'A rich and enchanting jasmine-scented perfume.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Woody Musk',
                'description' => 'A masculine perfume with woody and musky notes.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Amber Glow',
                'description' => 'A warm and captivating amber-based fragrance.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Patchouli Dream',
                'description' => 'A bold and earthy patchouli perfume for unique individuals.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Mint Breeze',
                'description' => 'A cooling and invigorating mint-scented fragrance.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Ocean Wave',
                'description' => 'A marine-inspired perfume with hints of sea breeze.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Golden Sandalwood',
                'description' => 'A luxurious sandalwood perfume with a golden touch.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Floral Fantasy',
                'description' => 'A bouquet of floral scents blended in one bottle.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Spicy Oud',
                'description' => 'A unique oud fragrance with spicy undertones.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Euphoria',
                'description' => 'A vibrant and uplifting fruity-floral perfume.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Classic Musk',
                'description' => 'An all-time favorite musky perfume for elegance.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Oriental Spice',
                'description' => 'An oriental perfume with rich spicy aromas.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Green Tea Bliss',
                'description' => 'A refreshing perfume with green tea and citrus notes.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Luxury Rose Oud',
                'description' => 'A luxurious blend of rose and oud fragrances.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
            [
                'name' => 'Coconut Paradise',
                'description' => 'A tropical coconut fragrance with sweet vanilla hints.',
                'price' => rand(100, 1000),
                'quantity' => rand(1, 100),
                'store_id' => 10,
            ],
        ];
        foreach ($data as $product){
            Product::create($product);

        }

    }}
